/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-22 23:51:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <style>\n");
      out.write("            html {\n");
      out.write("                background: #f7f9ff;\n");
      out.write("                font-size: 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .errorPageRap {\n");
      out.write("                text-align: center;\n");
      out.write("                margin: 5rem 0 13rem 0;\n");
      out.write("            }\n");
      out.write("            .errorPageRap .holoContainer {\n");
      out.write("                position: relative;\n");
      out.write("                width: 25.8rem;\n");
      out.write("                height: 40rem;\n");
      out.write("                margin: 0 0 30rem 0;\n");
      out.write("                display: inline-block;\n");
      out.write("                vertical-align: middle;\n");
      out.write("            }\n");
      out.write("            .errorPageRap h1 {\n");
      out.write("                font-family: 'Roboto', Arial;\n");
      out.write("                text-align: left;\n");
      out.write("                font-size: 2.8rem;\n");
      out.write("                font-weight: 400;\n");
      out.write("                color: #506280;\n");
      out.write("                line-height: 5.4rem;\n");
      out.write("                display: inline-block;\n");
      out.write("                vertical-align: text-bottom;\n");
      out.write("                margin: 0;\n");
      out.write("                margin-left: 4rem;\n");
      out.write("                width: 50%;\n");
      out.write("                min-width: 43.6rem;\n");
      out.write("                max-width: 64rem;\n");
      out.write("            }\n");
      out.write("            .errorPageRap h1 span {\n");
      out.write("                display: inline-block;\n");
      out.write("                width: 3rem;\n");
      out.write("            }\n");
      out.write("            .errorPageRap h1 span img {\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("            .errorPageRap h1 a {\n");
      out.write("                color: #404a5d;\n");
      out.write("                font-size: 3.3rem;\n");
      out.write("                text-decoration: none;\n");
      out.write("                font-weight: 900;\n");
      out.write("                transition: all .2s ease;\n");
      out.write("            }\n");
      out.write("            .errorPageRap h1 a:hover {\n");
      out.write("                opacity: .6;\n");
      out.write("            }\n");
      out.write("            .errorPageRap .holoContainer > img {\n");
      out.write("                position: absolute;\n");
      out.write("                top: 0;\n");
      out.write("                left: 1.4rem;\n");
      out.write("                z-index: 999;\n");
      out.write("                width: 86%;\n");
      out.write("            }\n");
      out.write("            .errorPageRap .holoContainer > img:nth-child(2),\n");
      out.write("            .errorPageRap .holoContainer > img:nth-child(3) {\n");
      out.write("                left: 1.2rem;\n");
      out.write("                top: 0;\n");
      out.write("                animation: glitch-anim-2 3s infinite linear alternate-reverse;\n");
      out.write("                clip: rect(0, 0, 0, 0);\n");
      out.write("            }\n");
      out.write("            .errorPageRap .holoContainer > img:nth-child(2) {\n");
      out.write("                left: .7rem;\n");
      out.write("                animation: glitch-anim-1 2s infinite linear alternate-reverse;\n");
      out.write("                width: 21rem;\n");
      out.write("            }\n");
      out.write("            .errorPageRap .holoContainer > img:nth-child(3) {\n");
      out.write("            }\n");
      out.write("            .errorPageRap .holoPad {\n");
      out.write("                position: absolute;\n");
      out.write("                bottom: -15rem;\n");
      out.write("                left: 50%;\n");
      out.write("                margin-left: -12.8rem;\n");
      out.write("                z-index: 998;\n");
      out.write("            }\n");
      out.write("            .errorPageRap .holoPad #sparks {\n");
      out.write("                opacity: .2;\n");
      out.write("                animation: twinkle 1.6s ease infinite;\n");
      out.write("                opacity: .4;\n");
      out.write("            }\n");
      out.write("            .errorPageRap .holoPad #holo_glow {\n");
      out.write("                animation: twinkle 10s 1s ease infinite;\n");
      out.write("                opacity: .7;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @keyframes twinkle {\n");
      out.write("                0% {\n");
      out.write("                    opacity: .7;\n");
      out.write("                }\n");
      out.write("                20% {\n");
      out.write("                    opacity: 1;\n");
      out.write("                }\n");
      out.write("                30% {\n");
      out.write("                    opacity: .6;\n");
      out.write("                }\n");
      out.write("                40% {\n");
      out.write("                    opacity: 1;\n");
      out.write("                }\n");
      out.write("                50% {\n");
      out.write("                    opacity: .4;\n");
      out.write("                }\n");
      out.write("                60% {\n");
      out.write("                    opacity: 1;\n");
      out.write("                }\n");
      out.write("                100% {\n");
      out.write("                    opacity: .7;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            @keyframes glitch-anim-1 {\n");
      out.write("                0% {\n");
      out.write("                    clip: rect(12.7rem, 2.5rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                6% {\n");
      out.write("                    clip: rect(1.5rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                13% {\n");
      out.write("                    clip: rect(18.9rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                20% {\n");
      out.write("                    clip: rect(2.1rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                26% {\n");
      out.write("                    clip: rect(11rem, 25.8rem, 40rem, 0);\n");
      out.write("                    opacity: .3;\n");
      out.write("                }\n");
      out.write("                33% {\n");
      out.write("                    clip: rect(17.5rem, 2220rem, -40rem, 0);\n");
      out.write("                }\n");
      out.write("                40% {\n");
      out.write("                    clip: rect(14rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                46% {\n");
      out.write("                    clip: rect(2.5rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                53% {\n");
      out.write("                    clip: rect(213.9rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                60% {\n");
      out.write("                    clip: rect(12.7rem, 25.8rem, 4rem, 0);\n");
      out.write("                    opacity: .3;\n");
      out.write("                }\n");
      out.write("                66% {\n");
      out.write("                    clip: rect(25.6rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                73% {\n");
      out.write("                    clip: rect(1.1rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                80% {\n");
      out.write("                    clip: rect(13.4rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                86% {\n");
      out.write("                    clip: rect(1.7rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                93% {\n");
      out.write("                    clip: rect(17.5rem, 25.8rem, 40rem, 0);\n");
      out.write("                    opacity: .3;\n");
      out.write("                }\n");
      out.write("                100% {\n");
      out.write("                    clip: rect(16.5rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            @keyframes glitch-anim-2 {\n");
      out.write("                0% {\n");
      out.write("                    clip: rect(12.7rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                6% {\n");
      out.write("                    clip: rect(15.4rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                13% {\n");
      out.write("                    clip: rect(1.8rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                20% {\n");
      out.write("                    clip: rect(13.8rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                26% {\n");
      out.write("                    clip: rect(1.1rem, 25.8rem, 28rem, 0);\n");
      out.write("                }\n");
      out.write("                33% {\n");
      out.write("                    clip: rect(3rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                40% {\n");
      out.write("                    clip: rect(1.1rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                46% {\n");
      out.write("                    clip: rect(15.2rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                53% {\n");
      out.write("                    clip: rect(13.9rem, 25.8rem, 30rem, 0);\n");
      out.write("                }\n");
      out.write("                60% {\n");
      out.write("                    clip: rect(40rem, 25.8rem, 40rem, 0);\n");
      out.write("                    opacity: .3;\n");
      out.write("                }\n");
      out.write("                66% {\n");
      out.write("                    clip: rect(15.6rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                73% {\n");
      out.write("                    clip: rect(1.1rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                80% {\n");
      out.write("                    clip: rect(1.3rem, 21.8rem, 35rem, 0);\n");
      out.write("                }\n");
      out.write("                86% {\n");
      out.write("                    clip: rect(17.3rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("                93% {\n");
      out.write("                    clip: rect(17.5rem, 25.8rem, 40rem, 0);\n");
      out.write("                    opacity: .3;\n");
      out.write("                }\n");
      out.write("                100% {\n");
      out.write("                    clip: rect(16.5rem, 25.8rem, 40rem, 0);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        </style>\n");
      out.write("        <script>\n");
      out.write("            $(document).ready(function ()\n");
      out.write("            {\n");
      out.write("                // scale on resize\n");
      out.write("                function fontResize() {\n");
      out.write("                    var resolution = 1440;\n");
      out.write("                    var font = 10;\n");
      out.write("\n");
      out.write("                    var width = $(window).width();\n");
      out.write("\n");
      out.write("                    var newFont = font * (width / resolution);\n");
      out.write("                    $(\"html\").css(\"font-size\", newFont);\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                $(document).ready(function () {\n");
      out.write("                    fontResize();\n");
      out.write("                    $(window).bind(\"resize\", function () {\n");
      out.write("                        fontResize();\n");
      out.write("                    });\n");
      out.write("                });\n");
      out.write("            })\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"errorPageRap\">\n");
      out.write("            <div class=\"holoContainer\">\n");
      out.write("                <img src=\"images/4041.png\">\n");
      out.write("                <img src=\"images/4042.png\">\n");
      out.write("                <img src=\"images/4043.png\">\n");
      out.write("                <svg class=\"holoPad\" width=\"25.6rem\" height=\"27.8rem\" viewBox=\"0 0 226 242\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\">\n");
      out.write("                <defs>\n");
      out.write("                <linearGradient x1=\"50%\" y1=\"100%\" x2=\"50%\" y2=\"0%\" id=\"linearGradient-1\">\n");
      out.write("                <stop stop-color=\"#F4F8FA\" offset=\"0%\"></stop>\n");
      out.write("                <stop stop-color=\"#A2D2E9\" offset=\"100%\"></stop>\n");
      out.write("                </linearGradient>\n");
      out.write("                <ellipse id=\"path-2\" cx=\"91\" cy=\"36.5\" rx=\"91\" ry=\"36.5\"></ellipse>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-3\">\n");
      out.write("                    <feOffset dx=\"0\" dy=\"4\" in=\"SourceAlpha\" result=\"shadowOffsetOuter1\"></feOffset>\n");
      out.write("                    <feColorMatrix values=\"0 0 0 0 0.672833111   0 0 0 0 0.78061935   0 0 0 0 0.829613095  0 0 0 1 0\" type=\"matrix\" in=\"shadowOffsetOuter1\"></feColorMatrix>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-4\">\n");
      out.write("                    <feOffset dx=\"0\" dy=\"-1\" in=\"SourceAlpha\" result=\"shadowOffsetInner1\"></feOffset>\n");
      out.write("                    <feComposite in=\"shadowOffsetInner1\" in2=\"SourceAlpha\" operator=\"arithmetic\" k2=\"-1\" k3=\"1\" result=\"shadowInnerInner1\"></feComposite>\n");
      out.write("                    <feColorMatrix values=\"0 0 0 0 1   0 0 0 0 1   0 0 0 0 1  0 0 0 0.5 0\" type=\"matrix\" in=\"shadowInnerInner1\"></feColorMatrix>\n");
      out.write("                </filter>\n");
      out.write("                <ellipse id=\"path-5\" cx=\"82.6398601\" cy=\"30.7894737\" rx=\"62.1223776\" ry=\"19.3859649\"></ellipse>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-6\">\n");
      out.write("                    <feMorphology radius=\"2.5\" operator=\"dilate\" in=\"SourceAlpha\" result=\"shadowSpreadOuter1\"></feMorphology>\n");
      out.write("                    <feOffset dx=\"0\" dy=\"1\" in=\"shadowSpreadOuter1\" result=\"shadowOffsetOuter1\"></feOffset>\n");
      out.write("                    <feGaussianBlur stdDeviation=\"2.5\" in=\"shadowOffsetOuter1\" result=\"shadowBlurOuter1\"></feGaussianBlur>\n");
      out.write("                    <feColorMatrix values=\"0 0 0 0 1   0 0 0 0 1   0 0 0 0 1  0 0 0 0.768851902 0\" type=\"matrix\" in=\"shadowBlurOuter1\"></feColorMatrix>\n");
      out.write("                </filter>\n");
      out.write("                <linearGradient x1=\"14.2258178%\" y1=\"52.965006%\" x2=\"86.6831166%\" y2=\"52.9650033%\" id=\"linearGradient-7\">\n");
      out.write("                <stop stop-color=\"#3BE2F7\" stop-opacity=\"0.392776268\" offset=\"0%\"></stop>\n");
      out.write("                <stop stop-color=\"#00F6F6\" stop-opacity=\"0.519339536\" offset=\"16.9423629%\"></stop>\n");
      out.write("                <stop stop-color=\"#009DFF\" stop-opacity=\"0.558111625\" offset=\"36.6410236%\"></stop>\n");
      out.write("                <stop stop-color=\"#26B0FF\" stop-opacity=\"0.587971664\" offset=\"51.9331952%\"></stop>\n");
      out.write("                <stop stop-color=\"#2292DB\" stop-opacity=\"0.617850828\" offset=\"67.2612404%\"></stop>\n");
      out.write("                <stop stop-color=\"#3EE5F4\" stop-opacity=\"0.646436303\" offset=\"81.9256218%\"></stop>\n");
      out.write("                <stop stop-color=\"#1A95FF\" stop-opacity=\"0.681668931\" offset=\"100%\"></stop>\n");
      out.write("                </linearGradient>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-8\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"9.94977679\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-9\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-10\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-11\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-12\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-13\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-14\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-15\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-16\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-17\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-18\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-19\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-20\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-21\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-22\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-23\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-24\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-25\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-26\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-27\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-28\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-29\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-30\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-31\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-32\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-33\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-34\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-35\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-36\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-37\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-38\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-39\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-40\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-41\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                <filter x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\" filterUnits=\"objectBoundingBox\" id=\"filter-42\">\n");
      out.write("                    <feGaussianBlur stdDeviation=\"1.03515625\" in=\"SourceGraphic\"></feGaussianBlur>\n");
      out.write("                </filter>\n");
      out.write("                </defs>\n");
      out.write("                <g id=\"Page-1\" stroke=\"none\" stroke-width=\"1\" fill=\"none\" fill-rule=\"evenodd\">\n");
      out.write("                <g id=\"Desktop-HD\" transform=\"translate(-479.000000, -302.000000)\">\n");
      out.write("                <g id=\"holo_pad\" transform=\"translate(498.000000, 324.000000)\">\n");
      out.write("                <g id=\"base\" transform=\"translate(0.000000, 141.000000)\">\n");
      out.write("                <g id=\"holo_lens_cover\">\n");
      out.write("                <use fill=\"black\" fill-opacity=\"1\" filter=\"url(#filter-3)\" xlink:href=\"#path-2\"></use>\n");
      out.write("                <use fill=\"url(#linearGradient-1)\" fill-rule=\"evenodd\" xlink:href=\"#path-2\"></use>\n");
      out.write("                <use fill=\"black\" fill-opacity=\"1\" filter=\"url(#filter-4)\" xlink:href=\"#path-2\"></use>\n");
      out.write("                </g>\n");
      out.write("                <g id=\"holo_ring_lense\" transform=\"translate(9.000000, 3.000000)\">\n");
      out.write("                <ellipse id=\"Oval-2\" fill=\"#9DB2AF\" cx=\"82.6398601\" cy=\"28.5087719\" rx=\"62.1223776\" ry=\"22.8070175\"></ellipse>\n");
      out.write("                <g id=\"Oval-2\">\n");
      out.write("                <use fill=\"black\" fill-opacity=\"1\" filter=\"url(#filter-6)\" xlink:href=\"#path-5\"></use>\n");
      out.write("                <use fill=\"#D3F9FD\" fill-rule=\"evenodd\" xlink:href=\"#path-5\"></use>\n");
      out.write("                </g>\n");
      out.write("                <path d=\"M82.308352,51.3070258 C120.616223,51.2889123 142.57421,39.650037 144.762238,34.7807018 C148.163881,27.210531 141.856773,22.7946167 133.083886,19.3859649 C121.938655,15.0555531 101.372497,16.2297437 85.4895105,16.2297437 C52.7540871,16.2297437 24.2799659,32.8039558 28.0392175,39.650037 C29.494342,42.300006 44.0004813,51.3251393 82.308352,51.3070258 Z\" id=\"Oval-2\" fill=\"#85F4FF\"></path>\n");
      out.write("                <g id=\"bolts\" fill=\"#AABCC5\">\n");
      out.write("                <ellipse id=\"Oval-7\" cx=\"82.0699301\" cy=\"62.7192982\" rx=\"4.55944056\" ry=\"2.28070175\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-8\" cx=\"132.223776\" cy=\"53.0263158\" rx=\"4.55944056\" ry=\"1.71052632\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-9\" cx=\"156.730769\" cy=\"41.622807\" rx=\"3.98951049\" ry=\"1.71052632\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-10\" cx=\"160.15035\" cy=\"25.0877193\" rx=\"2.84965035\" ry=\"1.14035088\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-11\" cx=\"147.041958\" cy=\"13.6842105\" rx=\"2.27972028\" ry=\"1.14035088\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-12\" cx=\"103.157343\" cy=\"0.570175439\" rx=\"1.70979021\" ry=\"0.570175439\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-13\" cx=\"39.8951049\" cy=\"4.56140351\" rx=\"2.27972028\" ry=\"1.14035088\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-6\" cx=\"28.4965035\" cy=\"54.1666667\" rx=\"4.55944056\" ry=\"1.71052632\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-5\" cx=\"4.55944056\" cy=\"38.2017544\" rx=\"4.55944056\" ry=\"1.71052632\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-3\" cx=\"16.527972\" cy=\"13.6842105\" rx=\"2.84965035\" ry=\"1.14035088\"></ellipse>\n");
      out.write("                <ellipse id=\"Oval-4\" cx=\"4.55944056\" cy=\"23.377193\" rx=\"3.41958042\" ry=\"1.71052632\"></ellipse>\n");
      out.write("                </g>\n");
      out.write("                </g>\n");
      out.write("                </g>\n");
      out.write("                <path d=\"M2.72749126,7.0974908 C2.02976525,2.73245828 5.01735668,-0.356276457 9.39575877,0.198013072 L178.122782,21.5582309 C182.50329,22.1127871 185.330836,26.077111 184.442533,30.3921522 L154.103095,177.769567 L150.783521,180.676785 C147.458001,183.58921 141.33267,186.994178 137.094749,188.213507 C137.094749,188.213507 112.445163,196.265581 92.5275028,196.02072 C72.6098428,195.775859 52.5096264,192.670969 42.8688096,187.508781 C33.2279929,182.346593 30.0084669,177.769567 30.0084669,177.769567 L2.72749126,7.0974908 Z\" id=\"holo_glow\" fill=\"url(#linearGradient-7)\" opacity=\"0.648890399\" filter=\"url(#filter-8)\"></path>\n");
      out.write("                <g id=\"sparks\" transform=\"translate(21.000000, 64.000000)\" fill=\"#FFFFFF\">\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-9)\" cx=\"104\" cy=\"111\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-10)\" cx=\"104\" cy=\"111\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-11)\" cx=\"96.5\" cy=\"114.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-12)\" cx=\"76.5\" cy=\"119.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-13)\" cx=\"63\" cy=\"98\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-14)\" cx=\"72.5\" cy=\"102.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-15)\" cx=\"92.5\" cy=\"99.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-16)\" cx=\"100\" cy=\"91\" r=\"1\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-17)\" cx=\"96.5\" cy=\"81.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-18)\" cx=\"106.5\" cy=\"73.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-19)\" cx=\"100.5\" cy=\"54.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-20)\" cx=\"82\" cy=\"52\" r=\"1\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-21)\" cx=\"123\" cy=\"56\" r=\"1\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-22)\" cx=\"121.5\" cy=\"64.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-23)\" cx=\"143\" cy=\"74\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-24)\" cx=\"150\" cy=\"51\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-25)\" cx=\"142.5\" cy=\"26.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-26)\" cx=\"154.5\" cy=\"18.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-27)\" cx=\"54\" cy=\"58\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-28)\" cx=\"49\" cy=\"49\" r=\"1\"></circle>\n");
      out.write("                <path d=\"M41.5,80 C42.3284271,80 43,79.3284271 43,78.5 C43,77.6715729 42.3284271,77 41.5,77 C40.6715729,77 40,77.6715729 40,78.5 C40,79.3284271 40.6715729,80 41.5,80 Z\" id=\"Oval-14\" filter=\"url(#filter-29)\"></path>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-30)\" cx=\"38.5\" cy=\"84.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-31)\" cx=\"38.5\" cy=\"79.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-32)\" cx=\"34.5\" cy=\"77.5\" r=\"1.5\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-33)\" cx=\"32\" cy=\"97\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-34)\" cx=\"29\" cy=\"105\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-35)\" cx=\"23\" cy=\"87\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-36)\" cx=\"14\" cy=\"62\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-37)\" cx=\"25\" cy=\"52\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-38)\" cx=\"29\" cy=\"29\" r=\"1\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-39)\" cx=\"2\" cy=\"14\" r=\"2\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-40)\" cx=\"20\" cy=\"26\" r=\"1\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-41)\" cx=\"26\" cy=\"21\" r=\"1\"></circle>\n");
      out.write("                <circle id=\"Oval-14\" filter=\"url(#filter-42)\" cx=\"65\" cy=\"2\" r=\"2\"></circle>\n");
      out.write("                </g>\n");
      out.write("                </g>\n");
      out.write("                </g>\n");
      out.write("                </g>\n");
      out.write("                </svg>\n");
      out.write("            </div>\n");
      out.write("            <h1>\n");
      out.write("                Bạn không có quyền truy cập trang Admin... <span><img src=\"images/sadFace.png\"></span>\n");
      out.write("                <br>\n");
      out.write("                Nếu bạn là Admin của website, hãy trở lại trang đăng nhập,<a href=\"index.jsp\">Đăng Nhập</a>\n");
      out.write("            </h1>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
