/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-22 23:54:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.User;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Header</title>\n");
      out.write("        <!-- javascripts -->\n");
      out.write("        <script src=\"js/jquery.js\"></script>\n");
      out.write("        <script src=\"js/jquery-ui-1.10.4.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery-1.8.3.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery-ui-1.9.2.custom.min.js\"></script>\n");
      out.write("        <!-- bootstrap -->\n");
      out.write("        <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("        <!-- nice scroll -->\n");
      out.write("        <script src=\"js/jquery.scrollTo.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\n");
      out.write("        <!-- charts scripts -->\n");
      out.write("        <script src=\"assets/jquery-knob/js/jquery.knob.js\"></script>\n");
      out.write("        <script src=\"js/jquery.sparkline.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js\"></script>\n");
      out.write("        <script src=\"js/owl.carousel.js\"></script>\n");
      out.write("        <!-- jQuery full calendar -->\n");
      out.write("        <script src=\"js/fullcalendar.min.js\"></script>\n");
      out.write("        <!-- Full Google Calendar - Calendar -->\n");
      out.write("        <script src=\"assets/fullcalendar/fullcalendar/fullcalendar.js\"></script>\n");
      out.write("        <!--script for this page only-->\n");
      out.write("        <script src=\"js/calendar-custom.js\"></script>\n");
      out.write("        <script src=\"js/jquery.rateit.min.js\"></script>\n");
      out.write("        <!-- custom select -->\n");
      out.write("        <script src=\"js/jquery.customSelect.min.js\"></script>\n");
      out.write("        <script src=\"assets/chart-master/Chart.js\"></script>\n");
      out.write("\n");
      out.write("        <!--custome script for all page-->\n");
      out.write("        <script src=\"js/scripts.js\"></script>\n");
      out.write("        <!-- custom script for this page-->\n");
      out.write("        <script src=\"js/sparkline-chart.js\"></script>\n");
      out.write("        <script src=\"js/easy-pie-chart.js\"></script>\n");
      out.write("        <script src=\"js/jquery-jvectormap-1.2.2.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery-jvectormap-world-mill-en.js\"></script>\n");
      out.write("        <script src=\"js/xcharts.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.autosize.min.js\"></script>\n");
      out.write("        <script src=\"js/jquery.placeholder.min.js\"></script>\n");
      out.write("        <script src=\"js/gdp-data.js\"></script>\n");
      out.write("        <script src=\"js/morris.min.js\"></script>\n");
      out.write("        <script src=\"js/sparklines.js\"></script>\n");
      out.write("        <script src=\"js/charts.js\"></script>\n");
      out.write("        <script src=\"js/jquery.slimscroll.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Bootstrap CSS -->\n");
      out.write("        <link href=\"cssAdmin/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("        <!-- bootstrap theme -->\n");
      out.write("        <link href=\"cssAdmin/bootstrap-theme.css\" rel=\"stylesheet\">\n");
      out.write("        <!--external css-->\n");
      out.write("        <!-- font icon -->\n");
      out.write("        <link href=\"cssAdmin/elegant-icons-style.css\" rel=\"stylesheet\" />\n");
      out.write("        <link href=\"cssAdmin/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("        <!-- full calendar css-->\n");
      out.write("        <link href=\"assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css\" rel=\"stylesheet\" />\n");
      out.write("        <link href=\"assets/fullcalendar/fullcalendar/fullcalendar.css\" rel=\"stylesheet\" />\n");
      out.write("        <!-- easy pie chart-->\n");
      out.write("        <link href=\"assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\n");
      out.write("        <!-- owl carousel -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"cssAdmin/owl.carousel.css\" type=\"text/css\">\n");
      out.write("        <link href=\"cssAdmin/jquery-jvectormap-1.2.2.css\" rel=\"stylesheet\">\n");
      out.write("        <!-- Custom styles -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"cssAdmin/fullcalendar.css\">\n");
      out.write("        <link href=\"cssAdmin/widgets.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"cssAdmin/style.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"cssAdmin/style-responsive.css\" rel=\"stylesheet\" />\n");
      out.write("        <link href=\"cssAdmin/xcharts.min.css\" rel=\" stylesheet\">\n");
      out.write("        <link href=\"cssAdmin/jquery-ui-1.10.4.min.css\" rel=\"stylesheet\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

            if (session.getAttribute("user") == null) {
                response.sendRedirect("404.jsp");
            }
        
      out.write("\n");
      out.write("        <header class=\"header dark-bg\" style=\"background-color: rgba(0, 0, 0, 0.34);\">\n");
      out.write("            <div class=\"toggle-nav\">\n");
      out.write("                <div class=\"icon-reorder tooltips\" data-original-title=\"Toggle Navigation\" data-placement=\"bottom\"><i class=\"icon_menu\"></i></div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--logo start-->\n");
      out.write("            <a href=\"indexAdmin.jsp\" class=\"logo\">Quản Lý Nhân Sự <span class=\"lite\">Và Tiền Lương</span></a>\n");
      out.write("            <!--logo end-->\n");
      out.write("\n");
      out.write("            <div class=\"nav search-row\" id=\"top_menu\" style=\"background-color: rgba(0, 0, 0, 0.34);\">\n");
      out.write("                <!--  search form start -->\n");
      out.write("                <ul class=\"nav top-menu\">\n");
      out.write("                    <li>\n");
      out.write("                        <form class=\"navbar-form\">\n");
      out.write("                            <input class=\"form-control\" style=\"background-color: rgba(0, 0, 0, 0.34);\" placeholder=\"Search\" type=\"text\">\n");
      out.write("                        </form>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <!--  search form end -->\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"top-nav notification-row\">\n");
      out.write("                <!-- notificatoin dropdown start-->\n");
      out.write("                <ul class=\"nav pull-right top-menu\">\n");
      out.write("\n");
      out.write("                    <!-- task notificatoin start -->\n");
      out.write("                    <li id=\"task_notificatoin_bar\" class=\"dropdown\">\n");
      out.write("                        <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\n");
      out.write("                            <i class=\"icon-task-l\"></i>\n");
      out.write("                            <span class=\"badge bg-important\">6</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu extended tasks-bar\">\n");
      out.write("                            <div class=\"notify-arrow notify-arrow-blue\"></div>\n");
      out.write("                            <li>\n");
      out.write("                                <p class=\"blue\">You have 6 pending letter</p>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"task-info\">\n");
      out.write("                                        <div class=\"desc\">Design PSD </div>\n");
      out.write("                                        <div class=\"percent\">90%</div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"progress progress-striped\">\n");
      out.write("                                        <div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"90\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 90%\">\n");
      out.write("                                            <span class=\"sr-only\">90% Complete (success)</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"task-info\">\n");
      out.write("                                        <div class=\"desc\">\n");
      out.write("                                            Project 1\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"percent\">30%</div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"progress progress-striped\">\n");
      out.write("                                        <div class=\"progress-bar progress-bar-warning\" role=\"progressbar\" aria-valuenow=\"30\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 30%\">\n");
      out.write("                                            <span class=\"sr-only\">30% Complete (warning)</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"task-info\">\n");
      out.write("                                        <div class=\"desc\">Digital Marketing</div>\n");
      out.write("                                        <div class=\"percent\">80%</div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"progress progress-striped\">\n");
      out.write("                                        <div class=\"progress-bar progress-bar-info\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%\">\n");
      out.write("                                            <span class=\"sr-only\">80% Complete</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"task-info\">\n");
      out.write("                                        <div class=\"desc\">Logo Designing</div>\n");
      out.write("                                        <div class=\"percent\">78%</div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"progress progress-striped\">\n");
      out.write("                                        <div class=\"progress-bar progress-bar-danger\" role=\"progressbar\" aria-valuenow=\"78\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 78%\">\n");
      out.write("                                            <span class=\"sr-only\">78% Complete (danger)</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <div class=\"task-info\">\n");
      out.write("                                        <div class=\"desc\">Mobile App</div>\n");
      out.write("                                        <div class=\"percent\">50%</div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"progress progress-striped active\">\n");
      out.write("                                        <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"50\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 50%\">\n");
      out.write("                                            <span class=\"sr-only\">50% Complete</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li class=\"external\">\n");
      out.write("                                <a href=\"#\">See All Tasks</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <!-- task notificatoin end -->\n");
      out.write("                    <!-- inbox notificatoin start-->\n");
      out.write("                    <li id=\"mail_notificatoin_bar\" class=\"dropdown\">\n");
      out.write("                        <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\n");
      out.write("                            <i class=\"icon-envelope-l\"></i>\n");
      out.write("                            <span class=\"badge bg-important\">5</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu extended inbox\">\n");
      out.write("                            <div class=\"notify-arrow notify-arrow-blue\"></div>\n");
      out.write("                            <li>\n");
      out.write("                                <p class=\"blue\">You have 5 new messages</p>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"photo\"><img alt=\"avatar\" src=\"./img/avatar-mini.jpg\"></span>\n");
      out.write("                                    <span class=\"subject\">\n");
      out.write("                                        <span class=\"from\">Greg  Martin</span>\n");
      out.write("                                        <span class=\"time\">1 min</span>\n");
      out.write("                                    </span>\n");
      out.write("                                    <span class=\"message\">\n");
      out.write("                                        I really like this admin panel.\n");
      out.write("                                    </span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"photo\"><img alt=\"avatar\" src=\"./img/avatar-mini2.jpg\"></span>\n");
      out.write("                                    <span class=\"subject\">\n");
      out.write("                                        <span class=\"from\">Bob   Mckenzie</span>\n");
      out.write("                                        <span class=\"time\">5 mins</span>\n");
      out.write("                                    </span>\n");
      out.write("                                    <span class=\"message\">\n");
      out.write("                                        Hi, What is next project plan?\n");
      out.write("                                    </span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"photo\"><img alt=\"avatar\" src=\"./img/avatar-mini3.jpg\"></span>\n");
      out.write("                                    <span class=\"subject\">\n");
      out.write("                                        <span class=\"from\">Phillip   Park</span>\n");
      out.write("                                        <span class=\"time\">2 hrs</span>\n");
      out.write("                                    </span>\n");
      out.write("                                    <span class=\"message\">\n");
      out.write("                                        I am like to buy this Admin Template.\n");
      out.write("                                    </span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"photo\"><img alt=\"avatar\" src=\"./img/avatar-mini4.jpg\"></span>\n");
      out.write("                                    <span class=\"subject\">\n");
      out.write("                                        <span class=\"from\">Ray   Munoz</span>\n");
      out.write("                                        <span class=\"time\">1 day</span>\n");
      out.write("                                    </span>\n");
      out.write("                                    <span class=\"message\">\n");
      out.write("                                        Icon fonts are great.\n");
      out.write("                                    </span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">See all messages</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <!-- inbox notificatoin end -->\n");
      out.write("                    <!-- alert notification start-->\n");
      out.write("                    <li id=\"alert_notificatoin_bar\" class=\"dropdown\">\n");
      out.write("                        <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\n");
      out.write("\n");
      out.write("                            <i class=\"icon-bell-l\"></i>\n");
      out.write("                            <span class=\"badge bg-important\">7</span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu extended notification\">\n");
      out.write("                            <div class=\"notify-arrow notify-arrow-blue\"></div>\n");
      out.write("                            <li>\n");
      out.write("                                <p class=\"blue\">You have 4 new notifications</p>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"label label-primary\"><i class=\"icon_profile\"></i></span>\n");
      out.write("                                    Friend Request\n");
      out.write("                                    <span class=\"small italic pull-right\">5 mins</span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"label label-warning\"><i class=\"icon_pin\"></i></span>\n");
      out.write("                                    John location.\n");
      out.write("                                    <span class=\"small italic pull-right\">50 mins</span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"label label-danger\"><i class=\"icon_book_alt\"></i></span>\n");
      out.write("                                    Project 3 Completed.\n");
      out.write("                                    <span class=\"small italic pull-right\">1 hr</span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">\n");
      out.write("                                    <span class=\"label label-success\"><i class=\"icon_like\"></i></span>\n");
      out.write("                                    Mick appreciated your work.\n");
      out.write("                                    <span class=\"small italic pull-right\"> Today</span>\n");
      out.write("                                </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\">See all notifications</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <!-- alert notification end-->\n");
      out.write("                    <!-- user login dropdown start-->\n");
      out.write("                    <li class=\"dropdown\">\n");
      out.write("                        <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\n");
      out.write("                            ");

                                User u = (User) session.getAttribute("user");
                                if (u != null) {
                            
      out.write("\n");
      out.write("                            <span class=\"profile-ava\">\n");
      out.write("                                <img alt=\"\" src=\"img/avatar1.jpg\" style=\"width: 50px;\">\n");
      out.write("                            </span>\n");
      out.write("                            <span class=\"username\">Xin chào,");
      out.print(u.getUsername());
      out.write("</span>\n");
      out.write("                            ");

                                }
                            
      out.write("\n");
      out.write("                            <b class=\"caret\"></b>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu extended logout\">\n");
      out.write("                            <div class=\"log-arrow-up\"></div>\n");
      out.write("                            <li class=\"eborder-top\">\n");
      out.write("                                <a href=\"#\"><i class=\"icon_profile\"></i> My Profile</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\"><i class=\"icon_mail_alt\"></i> My Inbox</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\"><i class=\"icon_clock_alt\"></i> Timeline</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"#\"><i class=\"icon_chat_alt\"></i> Chats</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"XuLyDangXuat\"><i class=\"icon_key_alt\"></i>Thoát</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"documentation.html\"><i class=\"icon_key_alt\"></i> Documentation</a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"documentation.html\"><i class=\"icon_key_alt\"></i> Documentation</a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <!-- user login dropdown end -->\n");
      out.write("                </ul>\n");
      out.write("                <!-- notificatoin dropdown end-->\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("        <!--header end-->\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
