/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2019-01-05 13:22:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lamlai_bai9_lib_isotope_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <!-- responsive--><meta name=\"viewport\" content=\"width = device-width,initial-scale = 1.0,maximum - scale = 1.0 ,user-scalable=no\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\" type=\"text/css\">\n");
      out.write("        <link  rel=\"stylesheet\" href=\"resources/css/bootstrap-grid.min.css\" type=\"text/css\" >\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/animate.css\">\n");
      out.write("        <style>\n");
      out.write("            *\n");
      out.write("            {\n");
      out.write("                margin:0;\n");
      out.write("                padding:0;\n");
      out.write("            }\n");
      out.write("            .noidung\n");
      out.write("            {\n");
      out.write("                display:flex;\n");
      out.write("                flex-wrap:wrap;\n");
      out.write("                justify-content: space-around;\n");
      out.write("            }\n");
      out.write("            .noidung .khoianh\n");
      out.write("            {\n");
      out.write("                width:22%;\n");
      out.write("                box-sizing:border-box;\n");
      out.write("            }\n");
      out.write("            .noidung .khoianh img\n");
      out.write("            {\n");
      out.write("                width:100%;\n");
      out.write("            }\n");
      out.write("            .noidung .khoianh figcaption\n");
      out.write("            {\n");
      out.write("                background:graytext;\n");
      out.write("                text-align: center;\n");
      out.write("                font-size:1.2em;\n");
      out.write("            }\n");
      out.write("            .noidung .nhandoi\n");
      out.write("            {\n");
      out.write("                width:50%;\n");
      out.write("            }\n");
      out.write("            @media (max-width:576px)\n");
      out.write("            {\n");
      out.write("                \n");
      out.write("                .noidung .khoianh\n");
      out.write("                {\n");
      out.write("                    width:100%;\n");
      out.write("                    \n");
      out.write("                }\n");
      out.write("                .noidung .nhandoi\n");
      out.write("                {\n");
      out.write("                    width:100%;\n");
      out.write("                    \n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            @media (min-width:577px) and (max-width:768px)\n");
      out.write("            {\n");
      out.write("                .noidung .khoianh\n");
      out.write("                {\n");
      out.write("                    width:50%;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            @media(min-width:769px) and (max-width:871px)\n");
      out.write("            {\n");
      out.write("                .noidung .khoianh\n");
      out.write("                {\n");
      out.write("                   width:30%;\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("            }\n");
      out.write("            @media(min-width:872px) and (max-width:1200px)\n");
      out.write("            {\n");
      out.write("                .noidung .khoianh\n");
      out.write("                {\n");
      out.write("                   width:22%;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <div class=\"tieude container text-xs-center\">\n");
      out.write("            <h1 class=\"display-3\" style=\"text-align:center;color:aqua;background:rgba(223,23,232,0.4);border-radius:6px;padding:5px;box-shadow:2px 2px 3px 1px rgba(0,0,0,0.4)\">\n");
      out.write("                Bài Đầu cho Masonry\n");
      out.write("            </h1>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"noidung\">\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/4041.png\">\n");
      out.write("                        <figcaption><h5>Tiêu đề ảnh </h5></figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/4042.png\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/4043.png\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/banner1.png\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh nhandoi\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/banner2.jpg\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/banner3.jpg\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/banner4.jpg\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh nhandoi\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/banner5.jpg\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/banner6.jpg\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/goto.jpg\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/logo.jpg\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"khoianh\">\n");
      out.write("                    <figure>\n");
      out.write("                        <img src=\"resources/images2/sadFace.png\">\n");
      out.write("                        <figcaption>Tiêu đề ảnh</figcaption>\n");
      out.write("                    </figure>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <script type=\"text/javascript\" src=\"resources/js/jquery-3.3.1.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"resources/js/bootstrap.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"resources/js/isotope.pkgd.min.js\"></script>\n");
      out.write("        <script src=\"https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"resources/js/imagesloaded.pkgd.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            jQuery(document).ready(function ()\n");
      out.write("            {\n");
      out.write("                $hieuung=$(\".noidung\").isotope(\n");
      out.write("                        {\n");
      out.write("                            itemSelector: '.khoianh',\n");
      out.write("                            fitler: '.khoianh'\n");
      out.write("\n");
      out.write("                        });\n");
      out.write("                        \n");
      out.write("                $hieuung.imagesLoaded().progress(function()\n");
      out.write("                {\n");
      out.write("                    $hieuung.isotope('layout');\n");
      out.write("                });        \n");
      out.write("                        \n");
      out.write("            });\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
